### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by pezzwit** [FransBouma/IgcsConnector#18]
Hi There! 

I started using this for BG3 today and after the first crash, my game now loads up with a black screen.
The game itself is working correctly, I hear the strt up noises and after a while I can click and hear it move to the main menu so I know the game is working fine, it's just a graphics issue.
If I remove this from the reshade folder then the game launches fine.
Can someone please advise if there is a workaround/fix for this?
Thanks :)

**Comment by FransBouma** [comment]
Go to the addons tab in the reshade overlay (it'll open with the shortcut key), you either see under the igcsconnector that a session is going on, click 'cancel' or if there's no session going on, click start depth of field session. You have to enable the camera to get this. 

Alternatively, remove the igcsconnector.ini file

**Comment by pezzwit** [comment]
Hi! 

Apologies it looks like this was a clasic case of PEBCAK... I just noticed it said no camera could be found under screenshot feautures etc. It looks like it wasn't wo0eking because I hadn't booted up the IGCS client yet. 
Booting up the IGCS client before enabling the IGCS connector seems to resolve the issue. 

Many thanks for your help, and for making these great tools!
